FROM mysql:8.0

ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=dreports
ENV MYSQL_USER=dreports
ENV MYSQL_PASSWORD=ftUk58_HoRs3sAzz8jk

COPY ../dreports-new.sql /docker-entrypoint-initdb.d/

EXPOSE 3306

CMD ["mysqld"] 