version: '3'

services:
  cloudreportserver:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8016:8016"  # TCP port
      - "8080:8080"  # HTTP port
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./updates:/app/updates
    # For debugging, don't restart automatically
    restart: "no"
    # Ensure console logging is visible
    tty: true
    stdin_open: true
    # Set environment variables
    environment:
      - PYTHONUNBUFFERED=1
      - CONFIG_FILE=/app/config/server.ini
    # Set logging options
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 