version: '3'

services:
  report_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: linux_cloud_report_server
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    environment:
      - LOG_LEVEL=INFO 