<?php
/** @package Dreports::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("DeviceMap.php");

/**
 * DeviceDAO provides object-oriented access to the t_devices table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Dreports::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class DeviceDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $Deviceid;

	/** @var string */
	public $Objectname;

	/** @var string */
	public $Objectid;

	/** @var string */
	public $Objectpswd;



}
?>