<?php
/** @package Dreports::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("SubscriptionMap.php");

/**
 * SubscriptionDAO provides object-oriented access to the t_subscriptions table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Dreports::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class SubscriptionDAO extends Phreezable
{
	/** @var string */
	public $Objectid;

	/** @var string */
	public $Objectname;

	/** @var date */
	public $Expiredate;

	/** @var string */
	public $Customername;

	/** @var string */
	public $Eik;

	/** @var string */
	public $Address;

	/** @var string */
	public $Hostname;

	/** @var string */
	public $Appip;

	/** @var string */
	public $Apptype;

	/** @var string */
	public $Appver;

	/** @var string */
	public $Appdbtype;

	/** @var int */
	public $Active;

	/** @var timestamp */
	public $Createdate;

	/** @var timestamp */
	public $Lastupdatedate;

	/** @var string */
	public $Comment;



}
?>